skysolar-main/routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

    Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('admin.user.logout');

    //CATEGORIES
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories/draw', [\App\Http\Controllers\Admin\CategoryController::class, 'draw'])->name('admin.categories.draw');
        Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('admin.categories.search');
        Route::get('/categories/list', [\App\Http\Controllers\Admin\CategoryController::class, 'list'])->name('admin.category.list');
        Route::post('/categories/bulk-actions', [\App\Http\Controllers\Admin\CategoryController::class, 'bulkActions']);
        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/page-contents/draw', [\App\Http\Controllers\Admin\PageContentController::class, 'draw'])->name('admin.page-contents.draw');
        Route::get('/page-contents/search', [\App\Http\Controllers\Admin\PageContentController::class, 'search'])->name('admin.page-contents.search');
        Route::get('/page-contents/list', [\App\Http\Controllers\Admin\PageContentController::class, 'list'])->name('admin.page-contents.list');
        Route::post('/page-contents/bulk-actions', [\App\Http\Controllers\Admin\PageContentController::class, 'bulkActions']);
        Route::resource('page-contents', \App\Http\Controllers\Admin\PageContentController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/form-submissions/draw', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'draw'])->name('admin.form-submissions.draw');
        Route::get('/form-submissions/search', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'search'])->name('admin.form-submissions.search');
        Route::get('/form-submissions/list', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'list'])->name('admin.form-submissions.list');
        Route::get('/form-submissions/{id}/downloadCv', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'downloadCv'])->name('admin.form-submissions.downloadCv');
        Route::post('/form-submissions/bulk-actions', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'bulkActions']);
        Route::resource('form-submissions', \App\Http\Controllers\Admin\FormSubmissionController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/blog/draw', [\App\Http\Controllers\Admin\BlogController::class, 'draw'])->name('admin.blog.draw');
        Route::get('/blog/search', [\App\Http\Controllers\Admin\BlogController::class, 'search'])->name('admin.blog.search');
        Route::get('/blog/list', [\App\Http\Controllers\Admin\BlogController::class, 'list'])->name('admin.blog.list');
        Route::post('/blog/bulk-actions', [\App\Http\Controllers\Admin\BlogController::class, 'bulkActions']);
        Route::resource('blog', \App\Http\Controllers\Admin\BlogController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories/draw', [\App\Http\Controllers\Admin\CategoryController::class, 'draw'])->name('admin.categories.draw');
        Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('admin.categories.search');
        Route::get('/categories/list', [\App\Http\Controllers\Admin\CategoryController::class, 'list'])->name('admin.categories.list');
        Route::post('/categories/bulk-actions', [\App\Http\Controllers\Admin\CategoryController::class, 'bulkActions']);
        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/examples/draw', [\App\Http\Controllers\Admin\ExampleController::class, 'draw'])->name('admin.examples.draw');
        Route::get('/examples/search', [\App\Http\Controllers\Admin\ExampleController::class, 'search'])->name('admin.examples.search');
        Route::get('/examples/list', [\App\Http\Controllers\Admin\ExampleController::class, 'list'])->name('admin.examples.list');
        Route::post('/examples/bulk-actions', [\App\Http\Controllers\Admin\ExampleController::class, 'bulkActions']);
        Route::resource('examples', \App\Http\Controllers\Admin\ExampleController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories-example/draw', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'draw'])->name('admin.categories-example.draw');
        Route::get('/categories-example/search', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'search'])->name('admin.categories-example.search');
        Route::get('/categories-example/list', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'list'])->name('admin.categories-example.list');
        Route::post('/categories-example/bulk-actions', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'bulkActions']);
        Route::resource('categories-example', \App\Http\Controllers\Admin\CategoryExampleController::class);
    });

    //Settings
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('settings/general', function () { return view('admin.settings.general'); })->name('settings.general');
        Route::resource('settings', \App\Http\Controllers\Admin\SettingController::class);
    });

    //ATTACHMENTS
    Route::middleware(['can:Manage Attachments'])->group(function () {
        Route::resource('attachments', \App\Http\Controllers\Admin\AttachmentController::class);
    });


    Route::post('/upload-file', [\App\Http\Controllers\Admin\MediaController::class, 'uploadFile'])->name('media.uploadFile');
    Route::post('/slugify', [\App\Http\Controllers\Admin\DashboardController::class, 'slugify'])->name('text.slugify');
});

skysolar-main/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index');
Route::get('/about', [App\Http\Controllers\Front\HomeController::class, 'about'])->name('about');
Route::get('/services', [App\Http\Controllers\Front\HomeController::class, 'services'])->name('services');
Route::get('/examples', [App\Http\Controllers\Front\HomeController::class, 'examples'])->name('examples');
Route::get('/examples/{slug}', [App\Http\Controllers\Front\HomeController::class, 'exampleSingle'])->name('examples-single');
Route::get('/roof', [App\Http\Controllers\Front\HomeController::class, 'roof'])->name('roof');
Route::get('/blog', [App\Http\Controllers\Front\HomeController::class, 'blog'])->name('blog');
Route::get('/blog/{slug}', [App\Http\Controllers\Front\HomeController::class, 'blogSingle'])->name('blog.single');
Route::get('/get-in-touch', [App\Http\Controllers\Front\HomeController::class, 'getInTouch'])->name('getInTouch');
Route::get('/career/{slug}', [App\Http\Controllers\Front\HomeController::class, 'careerSingle'])->name('career-single');

Route::post('/form-submit', [App\Http\Controllers\Front\FormSubmissionController::class, 'form'])->name('front.formSubmit');

skysolar-main/app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $guarded = [];
}

skysolar-main/app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\SettingsService;
use Illuminate\Http\Request;

class SettingController extends Controller
{

    private $settingsService;

    public function __construct(SettingsService $settings)
    {
        $this->settingsService = $settings;
    }

    public function index()
    {
        return redirect(route('settings.general'));
    }

    public function store(Request $request)
    {

        $settings = $request->all();

        foreach ($settings as $key => $setting) {
            if ($setting && in_array($key, ['chart_per_solar','chart_post_solar','chart_years'])) {
                $setting = explode(',', $setting);
            }


            $this->settingsService->save($key, $setting);

        }

        return redirect()->back()->withSuccess('Successfully Updated!');
    }
}

skysolar-main/resources/views/admin/settings/general.blade.php
@extends('layouts.admin')

@section('title', 'General Settings')

@section('content')
    <div class="content-wrapper admin-pages-edit-content">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-4">
                    <div class="col-md-6">
                        <h1>General settings</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="content container-fluid">
            <form id="create-form" action="{{route('settings.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-9 main-content--large">
                        <div class="row">
                            <div class="col-12 card card-default main-card">
                                <div class="card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <label for="phone_number">Phone Number</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="phone_number" type="number" name="phone_number" value="{{$settings->get('phone_number') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="phone_number_format">Phone Number With Format</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="phone_number_format" type="text" name="phone_number_format" value="{{$settings->get('phone_number_format') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="email">E-mail</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="email" type="email" name="email" value="{{$settings->get('email') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="latitude">Latitude</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="latitude" type="text" name="latitude" value="{{$settings->get('latitude') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="longitude">Longitude</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="longitude" type="text" name="longitude" value="{{$settings->get('longitude') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="google_map_key">Google map Key</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="google_map_key" type="text" name="google_map_key" value="{{$settings->get('google_map_key') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="location">Location</label>
                                            <div class="input-group-sm">
                                                <input class="form-control" id="location" type="text" name="location" value="{{$settings->get('location') }}">
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="chart_per_solar">Per-Solar Chart Prices</label>
                                            <div class="input-group-sm">
                                                <input class="form-control chart-inputs" id="chart_per_solar" type="text" name="chart_per_solar" value="{{ implode(',', $settings->get('chart_per_solar')) }}">
                                                <span></span>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="chart_post_solar">Post-Solar Chart Prices</label>
                                            <div class="input-group-sm">
                                                <input class="form-control chart-inputs" id="chart_post_solar" type="text" name="chart_post_solar" value="{{implode(',', $settings->get('chart_post_solar')) }}">
                                                <span></span>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <label for="chart_years">Chart Years</label>
                                            <div class="input-group-sm">
                                                <input class="form-control chart-inputs" id="chart_years" type="text" name="chart_years" value="{{implode(',', $settings->get('chart_years')) }}">
                                                <span></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 main-content--small">
                        <div class="row">
                            <div class="col-12">
                                <div class="card card-default main-card">
                                    <div class="card-header" data-card-widget="collapse">
                                        <span>Actions</span>
                                    </div>
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-4 text-right">
                                                <button class="btn btn-sm btn-primary" form="create-form" type="submit">Update</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
@endsection
@section('scripts')
    <script>
        $(document).ready(function () {
            $('.chart-inputs').on('change', function () {
                const values = $(this).val().split(',').filter(i => {
                    return i && !isNaN(parseInt(i))
                })
                console.log(values);
                if (values.length < 25) {
                    $(this).next('span').css('color', 'red')
                    $(this).next('span').text(`Count of input value most be 25 Current: ${values.length}`)
                } else if (values.length === 25){
                    $(this).next('span').css('color', '')
                    $(this).next('span').text(``)
                }
            })
        })
    </script>
@endsection