routes/admin.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

    Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('admin.user.logout');

    //CATEGORIES
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories/draw', [\App\Http\Controllers\Admin\CategoryController::class, 'draw'])->name('admin.categories.draw');
        Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('admin.categories.search');
        Route::get('/categories/list', [\App\Http\Controllers\Admin\CategoryController::class, 'list'])->name('admin.category.list');
        Route::post('/categories/bulk-actions', [\App\Http\Controllers\Admin\CategoryController::class, 'bulkActions']);
        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/page-contents/draw', [\App\Http\Controllers\Admin\PageContentController::class, 'draw'])->name('admin.page-contents.draw');
        Route::get('/page-contents/search', [\App\Http\Controllers\Admin\PageContentController::class, 'search'])->name('admin.page-contents.search');
        Route::get('/page-contents/list', [\App\Http\Controllers\Admin\PageContentController::class, 'list'])->name('admin.page-contents.list');
        Route::post('/page-contents/bulk-actions', [\App\Http\Controllers\Admin\PageContentController::class, 'bulkActions']);
        Route::resource('page-contents', \App\Http\Controllers\Admin\PageContentController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/form-submissions/draw', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'draw'])->name('admin.form-submissions.draw');
        Route::get('/form-submissions/search', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'search'])->name('admin.form-submissions.search');
        Route::get('/form-submissions/list', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'list'])->name('admin.form-submissions.list');
        Route::get('/form-submissions/{id}/downloadCv', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'downloadCv'])->name('admin.form-submissions.downloadCv');
        Route::post('/form-submissions/bulk-actions', [\App\Http\Controllers\Admin\FormSubmissionController::class, 'bulkActions']);
        Route::resource('form-submissions', \App\Http\Controllers\Admin\FormSubmissionController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/blog/draw', [\App\Http\Controllers\Admin\BlogController::class, 'draw'])->name('admin.blog.draw');
        Route::get('/blog/search', [\App\Http\Controllers\Admin\BlogController::class, 'search'])->name('admin.blog.search');
        Route::get('/blog/list', [\App\Http\Controllers\Admin\BlogController::class, 'list'])->name('admin.blog.list');
        Route::post('/blog/bulk-actions', [\App\Http\Controllers\Admin\BlogController::class, 'bulkActions']);
        Route::resource('blog', \App\Http\Controllers\Admin\BlogController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories/draw', [\App\Http\Controllers\Admin\CategoryController::class, 'draw'])->name('admin.categories.draw');
        Route::get('/categories/search', [\App\Http\Controllers\Admin\CategoryController::class, 'search'])->name('admin.categories.search');
        Route::get('/categories/list', [\App\Http\Controllers\Admin\CategoryController::class, 'list'])->name('admin.categories.list');
        Route::post('/categories/bulk-actions', [\App\Http\Controllers\Admin\CategoryController::class, 'bulkActions']);
        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/examples/draw', [\App\Http\Controllers\Admin\ExampleController::class, 'draw'])->name('admin.examples.draw');
        Route::get('/examples/search', [\App\Http\Controllers\Admin\ExampleController::class, 'search'])->name('admin.examples.search');
        Route::get('/examples/list', [\App\Http\Controllers\Admin\ExampleController::class, 'list'])->name('admin.examples.list');
        Route::post('/examples/bulk-actions', [\App\Http\Controllers\Admin\ExampleController::class, 'bulkActions']);
        Route::resource('examples', \App\Http\Controllers\Admin\ExampleController::class);
    });

    //Page Contents
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('/categories-example/draw', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'draw'])->name('admin.categories-example.draw');
        Route::get('/categories-example/search', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'search'])->name('admin.categories-example.search');
        Route::get('/categories-example/list', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'list'])->name('admin.categories-example.list');
        Route::post('/categories-example/bulk-actions', [\App\Http\Controllers\Admin\CategoryExampleController::class, 'bulkActions']);
        Route::resource('categories-example', \App\Http\Controllers\Admin\CategoryExampleController::class);
    });

    //Settings
    Route::middleware(['can:Manage Pages'])->group(function () {
        Route::get('settings/general', function () { return view('admin.settings.general'); })->name('settings.general');
        Route::resource('settings', \App\Http\Controllers\Admin\SettingController::class);
    });

    //ATTACHMENTS
    Route::middleware(['can:Manage Attachments'])->group(function () {
        Route::resource('attachments', \App\Http\Controllers\Admin\AttachmentController::class);
    });


    Route::post('/upload-file', [\App\Http\Controllers\Admin\MediaController::class, 'uploadFile'])->name('media.uploadFile');
    Route::post('/slugify', [\App\Http\Controllers\Admin\DashboardController::class, 'slugify'])->name('text.slugify');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', [App\Http\Controllers\Front\HomeController::class, 'index'])->name('index');
Route::get('/about', [App\Http\Controllers\Front\HomeController::class, 'about'])->name('about');
Route::get('/services', [App\Http\Controllers\Front\HomeController::class, 'services'])->name('services');
Route::get('/examples', [App\Http\Controllers\Front\HomeController::class, 'examples'])->name('examples');
Route::get('/examples/{slug}', [App\Http\Controllers\Front\HomeController::class, 'exampleSingle'])->name('examples-single');
Route::get('/roof', [App\Http\Controllers\Front\HomeController::class, 'roof'])->name('roof');
Route::get('/blog', [App\Http\Controllers\Front\HomeController::class, 'blog'])->name('blog');
Route::get('/blog/{slug}', [App\Http\Controllers\Front\HomeController::class, 'blogSingle'])->name('blog.single');
Route::get('/get-in-touch', [App\Http\Controllers\Front\HomeController::class, 'getInTouch'])->name('getInTouch');
Route::get('/career/{slug}', [App\Http\Controllers\Front\HomeController::class, 'careerSingle'])->name('career-single');

Route::post('/form-submit', [App\Http\Controllers\Front\FormSubmissionController::class, 'form'])->name('front.formSubmit');

resources/views/admin/partials/header.blade.php
<header class="admin-header position-fixed">
    <div class="visit-site-box">
        <a href="/">
            <i class="fas fa-home"></i>
            Sky Solar
        </a>
        <ul class="list">
            <li>
                <a href="/">Visit Site</a>
            </li>
        </ul>
    </div>
    <div class="admin-account-box position-relative">
        <div class="admin-name-box">
            <p>Howdy, Admin</p>
        </div>
        <img loading="lazy"  src="{{asset('/images/static/Frame.png')}}" class="admin-image">

        <div class="logout-box position-absolute">
            <div class="logout-box--inner">
                <div class="user-info">
                    <p class="name">Admin</p>
                </div>
                <div class="user-actions">
                    <a href="{{route('admin.user.logout')}}" role="button">
                        <span>Log Out</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/admin/partials/sidebar.blade.php
<aside class="main-sidebar-admin">
    <!-- Sidebar -->
    <div class="sidebar-admin">
        <!-- Sidebar Menu -->
        <nav>
            <ul class="nav nav-pills nav-sidebar flex-column pt-4" data-widget="treeview" role="menu" data-accordion="false">
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('attachments.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Media</span>
                        </a>
                    </li>
                @endcan
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('page-contents.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Page Contents</span>
                        </a>
                    </li>
                @endcan
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('form-submissions.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Form Submissions</span>
                        </a>
                    </li>
                @endcan
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('blog.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Blog</span>
                        </a>
                    </li>
                    <li class="nav-item menu">
                        <a href="{{route('categories.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Categories</span>
                        </a>
                    </li>
                @endcan
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('examples.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Example</span>
                        </a>
                    </li>
                    <li class="nav-item menu">
                        <a href="{{route('categories-example.index')}}" class="nav-link">
                            <i class="fas fa-images"></i>
                            <span>Categories Example</span>
                        </a>
                    </li>
                @endcan
                @can('Manage Pages')
                    <li class="nav-item menu">
                        <a href="{{route('settings.general')}}" class="nav-link"><i
                                class="nav-icon fas fa-sliders-h"></i><span>Settings</span></a>
                        <div class="subMenu">
                            <a href="{{route('settings.general')}}" class="nav-link"><span>General</span></a>
                        </div>
                    </li>
                @endcan
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>